kind: ConfigMap
apiVersion: v1
metadata:
  name: root-crontab
  namespace: {{namespace}}
data:
  root: |
        # do daily/weekly/monthly maintenance
        # min   hour    day     month   weekday command
        */5     *       *       *       *       /usr/local/bin/psql -U hass -c "call pwpl_update_event_table_cron();"
        */15    *       *       *       *       run-parts /etc/periodic/15min
        0       *       *       *       *       run-parts /etc/periodic/hourly
        0       2       *       *       *       run-parts /etc/periodic/daily
        0       3       *       *       6       run-parts /etc/periodic/weekly
        0       5       1       *       *       run-parts /etc/periodic/monthly

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-database
  namespace: {{namespace}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: microk8s-hostpath

---
apiVersion: v1
kind: Secret
metadata:
  name: hass-database
  namespace: {{namespace}}
type: Opaque
stringData:
  POSTGRES_HOST: database
  POSTGRES_DB: hass
  POSTGRES_USER: hass
  POSTGRES_PASSWORD: hassuspwd

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tsdb
  namespace: {{namespace}}
  labels:
    app: tsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsdb
  template:
    metadata:
      labels:
        app: tsdb
    spec:
      containers:
      - name: tsdb
        image: docker.io/timescale/timescaledb:latest-pg15
        envFrom:
          - secretRef:
              name: hass-database
        ports:
          - containerPort:  5432
        volumeMounts:
        - name: hass-database
          mountPath: /var/lib/postgresql/data
        - name: root-crontab
          mountPath: /etc/crontabs/root
          subPath: root
        - name: dshm
          mountPath: /dev/shm
        lifecycle:
          postStart:
            exec: 
              command: ['/usr/sbin/crond']
      volumes:
      - name: hass-database
        persistentVolumeClaim:
          claimName: hass-database
      - name: root-crontab
        configMap:
          name: root-crontab
      - name: dshm
        emptyDir:
          medium: Memory

---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: {{namespace}}
spec:
  type: NodePort
  selector:
    app: tsdb
  ports:
  - protocol: TCP
    nodePort: 30021
    port: 5432
    targetPort: 5432




















