---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: {{namespace}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: {{namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/name: mosquitto
data:
  mosquitto.conf: |
    listener {{mqtt_port}}
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data
    autosave_interval 1800

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: {{namespace}}
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: "eclipse-mosquitto:2.0.14"
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt
              containerPort: {{mqtt_port}}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /mosquitto/data
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
          livenessProbe:
            tcpSocket:
              port: {{mqtt_port}}
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 60
          readinessProbe:
            tcpSocket:
              port: {{mqtt_port}}
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 60
          startupProbe:
            tcpSocket:
              port: {{mqtt_port}}
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data
        - name: mosquitto-config
          configMap:
            name: mosquitto-config

---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: {{namespace}}
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.181.81
  ports:
  - name: mqtt
    port: {{mqtt_port}}
    protocol: TCP
    targetPort: {{mqtt_port}}
  selector:
    app.kubernetes.io/name: mosquitto
