-- Table: public.pwpl_systems

-- DROP TABLE IF EXISTS public.pwpl_systems;

CREATE TABLE IF NOT EXISTS public.pwpl_systems
(
    id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    installation_id smallint NOT NULL,
    code character varying(32) COLLATE pg_catalog."default" NOT NULL,
    description character varying(250) COLLATE pg_catalog."default",
    is_solar character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '0'::bpchar,
    is_inverter character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '0'::bpchar,
    is_batt character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '0'::bpchar,
    CONSTRAINT pwpl_systems_pkey PRIMARY KEY (id),
    CONSTRAINT pwpl_systems_code_key UNIQUE (code),
    CONSTRAINT pwpl_systems_installation_id_fkey FOREIGN KEY (installation_id)
        REFERENCES public.pwpl_installations (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.pwpl_systems
    OWNER to hass;
