-- Table: public.pwpl_installations

-- DROP TABLE IF EXISTS public.pwpl_installations;

CREATE TABLE IF NOT EXISTS public.pwpl_installations
(
    id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    code character varying(32) COLLATE pg_catalog."default" NOT NULL,
    mqtt_code character(4) COLLATE pg_catalog."default" NOT NULL DEFAULT '00'::bpchar,
    coordinates point,
    description character varying(250) COLLATE pg_catalog."default",
    CONSTRAINT pwpl_installations_pkey PRIMARY KEY (id),
    CONSTRAINT pwpl_installations_code_key UNIQUE (code)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.pwpl_installations
    OWNER to hass;
